[package]
name = "langbardo"
version = "0.1.0"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cassowary = "0.3.0"

[dev-dependencies]
assert_approx_eq = "1.1.0"